In [1]:
!pip install requests beautifulsoup4

Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (2.32.3)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (4.12.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests) (2024.8.30)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4) (2.6)

In [2]:
import requests
from bs4 import BeautifulSoup
import lxml
import pandas as pd

In [3]:
url_total_jobs = 'https://www.totaljobs.com/jobs/in-uk?cid=SEA_GO_UK-TJ-Gen---PMAX%7C%5BA%5D_c_PMAX_PMAX_PMAX_PMAX001&gad_source=1&gclid=CjwKCAiA3ZC6BhBaEiwAeqfvymWVn6IyAfM_rZuOHGCvU2vvOSUajlsdSfWwybIZAK8BBnC2QdLCJRoChygQAvD_BwE'
response_total_jobs = requests.get(url_total_jobs)
html_content_total_jobs = response_total_jobs.text

In [4]:
soup = BeautifulSoup(html_content_total_jobs, 'lxml')

total_jobs_title = soup.find_all(name='div', class_='res-nehv70')
total_jobs_company_name = soup.find_all(name='span', class_='res-btchsq')
total_jobs_salary = soup.find_all(name='span', attrs={'data-at': 'job-item-salary-info'})

total_jobs_title_storage = []
total_jobs_company_name_storage = []
total_jobs_salary_storage = []

for title in total_jobs_title:
  total_jobs_title_storage.append(title.text)

for name in total_jobs_company_name:
  total_jobs_company_name_storage.append(name.text)

for salary in total_jobs_salary:
  total_jobs_salary_storage.append(salary.text)

In [5]:
total_jobs_title_storage
total_jobs_title_storage_2 = []

for i in range(0, len(total_jobs_title_storage), 2):
  total_jobs_title_storage_2.append(total_jobs_title_storage[i])

In [6]:
len(total_jobs_title_storage_2)

25

In [7]:
total_jobs_title_storage_2

['Science Management Graduate Scheme',
 'Hospitality Manager',
 'Learning and Development Manager',
 'Live In Care Assistant',
 'Work from home as an Online English as a Foreign Language Tutor - Part',
 'Online Tutor - Part Time & No experience',
 'Trainee Protection Adviser',
 'Blinds & Curtains Fitter',
 'Experienced Protection Adviser',
 'Retail Graduate Manager',
 'Apprentice HGV Technician',
 'SAP Support Analyst',
 'Business Development Manager',
 'Flameproof Certification Engineer',
 'Inspections Engineer',
 'Learning and Development Partner',
 'Lead AI Data Engineer',
 'Lead AI Solutions Architect',
 'GMP Production Operator',
 'Project Coordinator',
 'Marketing Manager Life Science',
 'National Sales Executive',
 'Head of Commercial Development',
 'Business Development Manager - Advisory Services',
 'Project Manager']

In [8]:
total_jobs_salary_storage

['From £25,705 to £28,816 per annum depending on location + benefits',
 'Up to £24,000 per annum plus generous benefit package including accomm',
 'Unspecified',
 '£910 per week (paid monthly) + a weekly food allowance of up to £49.00',
 'From £20 to £40 per hour',
 'From £20 to £40 per hour',
 '£25,000 per annum plus great bonus earning opportunities',
 'From £25,000 to £50,000 per annum',
 '£30,000 per annum plus great bonus earning opportunities',
 'Competitive',
 '£11.44 per hour',
 'From £45,000 to £55,000 per annum + Benefits',
 'From £32,000 to £34,000 per annum DOE',
 'Unspecified',
 'Unspecified',
 'Competitive',
 'Competitive',
 'Competitive',
 'Unspecified',
 '£30,000 per annum',
 'Unspecified',
 'Up to £38,000 per annum depending on experience',
 '£65,000 per annum',
 'Competitive',
 'Unspecified']

In [9]:
total_jobs_company_name

total_jobs_company_name_storage_2 = []

for i in range(0, len(total_jobs_company_name_storage), 3):
  total_jobs_company_name_storage_2.append(total_jobs_company_name_storage[i])

In [10]:
len(total_jobs_company_name_storage_2)

25

In [11]:
total_jobs_company_name_storage_2

['Rentokil Pest Control',
 'FIBO',
 'Culina Group Limited',
 'SPINAL HOMECARE SERVICES LTD',
 'Findtutors',
 'Findtutors',
 'London & Country Mortgages',
 'Hillarys Blinds',
 'London & Country Mortgages',
 'Asda',
 'Culina Group',
 'Essential Recruitment',
 'City & Guilds',
 'SGS United Kingdom Limited',
 'SGS United Kingdom Limited',
 'Culina Group',
 'Sopra Steria Limited',
 'Sopra Steria Limited',
 'SGS United Kingdom Limited',
 'Cogent Skills',
 'SGS United Kingdom Limited',
 'SGS United Kingdom Limited',
 'SGS United Kingdom Limited',
 'SGS United Kingdom Limited',
 'SGS United Kingdom Limited']

In [12]:
# total_jobs_company_name

# total_jobs_company_name_2 = []

# for i in range(0, len(total_jobs_company_name)):
#   if 'UK' in total_jobs_company_name[i].text:
#     continue
#   else:
#     total_jobs_company_name_2.append(total_jobs_company_name[i].text)

In [13]:
len(total_jobs_title_storage_2)

25

In [14]:
total_jobs_dataframe = pd.DataFrame(
    {'Title': total_jobs_title_storage_2,
     'Company Name': total_jobs_company_name_storage_2,
     'Salary': total_jobs_salary_storage
     })

In [15]:
total_jobs_dataframe

,Title,Company Name,Salary
0,Science Management Graduate Scheme,Rentokil Pest Control,"From £25,705 to £28,816 per annum depending on..."
1,Hospitality Manager,FIBO,"Up to £24,000 per annum plus generous benefit ..."
2,Learning and Development Manager,Culina Group Limited,Unspecified
3,Live In Care Assistant,SPINAL HOMECARE SERVICES LTD,£910 per week (paid monthly) + a weekly food a...
4,Work from home as an Online English as a Forei...,Findtutors,From £20 to £40 per hour
5,Online Tutor - Part Time & No experience,Findtutors,From £20 to £40 per hour
6,Trainee Protection Adviser,London & Country Mortgages,"£25,000 per annum plus great bonus earning opp..."
7,Blinds & Curtains Fitter,Hillarys Blinds,"From £25,000 to £50,000 per annum"
8,Experienced Protection Adviser,London & Country Mortgages,"£30,000 per annum plus great bonus earning opp..."
9,Retail Graduate Manager,Asda,Competitive
10,Apprentice HGV Technician,Culina Group,£11.44 per hour
11,SAP Support Analyst,Essential Recruitment,"From £45,000 to £55,000 per annum + Benefits"
12,Business Development Manager,City & Guilds,"From £32,000 to £34,000 per annum DOE"
13,Flameproof Certification Engineer,SGS United Kingdom Limited,Unspecified
14,Inspections Engineer,SGS United Kingdom Limited,Unspecified
15,Learning and Development Partner,Culina Group,Competitive
16,Lead AI Data Engineer,Sopra Steria Limited,Competitive
17,Lead AI Solutions Architect,Sopra Steria Limited,Competitive
18,GMP Production Operator,SGS United Kingdom Limited,Unspecified
19,Project Coordinator,Cogent Skills,"£30,000 per annum"
20,Marketing Manager Life Science,SGS United Kingdom Limited,Unspecified
21,National Sales Executive,SGS United Kingdom Limited,"Up to £38,000 per annum depending on experience"
22,Head of Commercial Development,SGS United Kingdom Limited,"£65,000 per annum"
23,Business Development Manager - Advisory Services,SGS United Kingdom Limited,Competitive
24,Project Manager,SGS United Kingdom Limited,Unspecified